services:
  - type: web
    name: randombot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: TOKEN
        sync: false
      - key: APP_ID
        sync: false
